### ISSUE TITLE
Causing flickering mouse

### ISSUE THREAD

**Issue by JakobDylanC** [hannesmann/vanillafixes#10]
Using VanillaFixes.exe is causing my mouse to flicker. Here are my video settings:
![image](https://user-images.githubusercontent.com/38699060/232922619-7d66b90d-9d2d-4ef3-a9cd-a505d2af4043.png)

**Comment by JakobDylanC** [comment]
Nevermind, I think it's a general issue with the higher refresh rate. Fixed by disabling hardware cursor

**Comment by hannesmann** [comment]
Yeah, the hardware cursor flickering issue always happens at high refresh rates. It's an engine bug. You can trigger it on Linux or old versions of Windows even without VanillaFixes. Closing this since it isn't a VanillaFixes issue.
