### ISSUE TITLE
Possible to use it for TBC 2.4.3?

### ISSUE THREAD

**Issue by Minnona** [hannesmann/vanillafixes#14]
And is there any need to?

**Comment by hannesmann** [comment]
There's a console variable in TBC that should do the same thing as VanillaFixes. Try setting this to 2 or 3: https://wowpedia.fandom.com/wiki/CVar_timingMethod

**Comment by Minnona** [comment]
Thanks, I'll check it out. Still need to be paired with dxvk right? Tried the latest dxvk ealier and sometimes the game would just freeze and crash.

**Comment by hannesmann** [comment]
DXVK can improve your FPS but it shouldn't make a massive difference. If the game crashes with DXVK installed, just delete it.
