### ISSUE TITLE
Windowed Black Screen

### ISSUE THREAD

**Issue by zaicopx** [hannesmann/vanillafixes#18]
Why do i get a black screen when actived windowed mode?

**Comment by hannesmann** [comment]
Hmm, probably an issue with DXVK. Have you tried the version without DXVK (vanillafixes-1.3.zip)? Make sure you delete d3d9.dll from the game folder.

**Comment by khold93** [comment]
what @hannesmann suggested worked for me.
I just made a new folder and moved d3d9.dll in there instead of deleting it, incase something went wrong.

**Comment by hannesmann** [comment]
Closing since the issue has been resolved.
