### ISSUE TITLE
Launch the game maximised if shortcut properties say so

### ISSUE THREAD

**Issue by wodim** [hannesmann/vanillafixes#19]
You can create a shortcut to wow.exe and configure it to launch maximised in the shortcut properties sheet. If you do that in the vanillafixes.exe shortcut, it doesn't work; the wow window is created restored. I know it's not a "bug" in the traditional sense of the word but it would be nice if it worked.

**Comment by hannesmann** [comment]
Not sure if this can be fixed. I assume Windows is looking for a window created by VanillaFixes.exe, but since the launcher exits and launches WoW.exe the shortcut properties aren't carried over.

**Comment by wodim** [comment]
You can use `GetStartupInfo`, and from the `STARTUPINFO` structure get the `wShowWindow` member and put it here https://github.com/hannesmann/vanillafixes/blob/d9242b23889d4123aedb74ea4e1e4b969ef8ab8b/src/launcher/launcher.c#L44

(I haven't tested this, I just did some googling)

**Comment by hannesmann** [comment]
Makes sense, I think you could use the `nCmdShow` parameter of `wWinMain` too. I'll look into this later but if you want to fix it I'll accept a PR.

**Comment by hannesmann** [comment]
I haven't tested this but it should work: https://github.com/hannesmann/vanillafixes/raw/shortcut-properties/bin/VanillaFixes.exe

**Comment by wodim** [comment]
Works fine. Thank you

**Comment by WuVenus** [comment]
> I haven't tested this but it should work: https://github.com/hannesmann/vanillafixes/raw/shortcut-properties/bin/VanillaFixes.exe

cannot open
