### ISSUE TITLE
Crashes DXVK on NVIDIA (windows)

### ISSUE THREAD

**Issue by sh3ppard** [hannesmann/vanillafixes#2]
System: Windows 10 22H2
Video Card: NVIDIA GT 650M

Launched the latest release.
![image](https://user-images.githubusercontent.com/121023853/209059649-648b0443-fd99-45c8-a3a1-9965b1acad3b.png)

**Comment by hannesmann** [comment]
Does it work if you use the regular version (vanillafixes-1.1.zip)? 

Driver updates for your GPU stopped in 2019 so maybe there's some incompatibility with the latest version of DXVK. You could try the [legacy](https://github.com/doitsujin/dxvk/releases/tag/v1.10.3) version. 

https://github.com/doitsujin/dxvk/wiki/Driver-support

**Comment by sh3ppard** [comment]
> Does it work if you use the regular version (vanillafixes-1.1.zip)?
Yes, it works without any errors.

> Driver updates for your GPU stopped in 2019 so maybe there's some incompatibility with the latest version of DXVK. You could try the [legacy](https://github.com/doitsujin/dxvk/releases/tag/v1.10.3) version.

I'll try, thx.

**Comment by sh3ppard** [comment]
[Legacy](https://github.com/doitsujin/dxvk/releases/tag/v1.10.3) version of driver helped.
