### ISSUE TITLE
Unable to load in Wowreeb

### ISSUE THREAD

**Issue by Rugara312** [hannesmann/vanillafixes#23]
I have updated the config but keep getting an error.

<?xml version="1.0" encoding="utf-8"?>
<wowreeb>

  <Config Name="ClearWDB" Value="1" />

  <Realm Name="Turtle WoW: Mysteries of Azeroth">

    <Exe Path="D:\Turtle WoW\WoW.exe" />
    <AuthServer Host="logon.turtle-wow.org" />
    
    <DLL Path="D:\Turtle WoW\VfPatcher.dll" Method="Load" />
    <DLL Path="D:\Turtle WoW\nampower.dll" Method="Load" />

  </Realm>
  
</wowreeb>

![error](https://github.com/hannesmann/vanillafixes/assets/86811599/8c7e8089-0376-44b9-bfb8-09f55f095042)

**Comment by Buggyswires** [comment]
I tried the same yesterday because i wanted to use Vanillafixes + ReShade and tried to prelaunch the VfPatcher.dll in WoWReeb

**Comment by hannesmann** [comment]
The `Method` field should be omitted for VanillaFixes:

```
<DLL Path="D:\Turtle WoW\VfPatcher.dll" />
<DLL Path="D:\Turtle WoW\nampower.dll" Method="Load" />
```

(That should probably be documented somewhere...)

**Comment by Buggyswires** [comment]
After i removed the Method field i get this

![image](https://github.com/hannesmann/vanillafixes/assets/43603807/358ddf15-0fd2-4ae0-af24-a7640f86b321)

**Comment by hannesmann** [comment]
VanillaFixes should definitely work with wowreeb since version 3.5 (https://github.com/namreeb/wowreeb/issues/20#issuecomment-1366997088). An error code of 5 means `ERROR_ACCESS_DENIED`, does it work if you try to inject any other DLL like nampower.dll?

**Comment by Buggyswires** [comment]
Yes, i was using nampower.dll only and that one was working (or at least didnt throw an error)

     <DLL Path="d:\<wow path>\VfPatcher.dll" /> 
     <DLL Path="d:\<wow path>\nampower-2.2\nampower.dll" Method="Load" />

<wow path> anonymized

**Comment by hannesmann** [comment]
Closing since I tested this again and it still works with the latest version.
