### ISSUE TITLE
132 Error

### ISSUE THREAD

**Issue by slicplaya** [hannesmann/vanillafixes#25]
![image](https://github.com/hannesmann/vanillafixes/assets/6567001/5856fc29-8183-4887-8c1e-4c958489d654)
Fresh Download of TWoW no addons nothing. starts up great. Soon as I dump all 4 Vanillafixes and start up i get the error. Any solutions?

**Comment by slicplaya** [comment]
The issue seems to be coming from the d3d9.dll

**Comment by hannesmann** [comment]
Duplicate of #24, I would recommend deleting DXVK and using NVIDIA's native DX9 drivers on a GTX 660
