### ISSUE TITLE
Missing files error when compiling

### ISSUE THREAD

**Issue by NoelHG** [hannesmann/vanillafixes#30]
I have new versions of visual studio and cmake, but cmake gives the following errors:

CMake Error at src/dll/CMakeLists.txt:10 (target_sources):
  Cannot find source file:
.../vanillafixes-1.3.1/minhook/src/buffer.c

and other files if I add buffer.c

Not sure if I missed anything?

**Comment by hannesmann** [comment]
You need `git submodule update --init`

**Comment by NoelHG** [comment]
yep that was it
