### ISSUE TITLE
VC redist dependency

### ISSUE THREAD

**Issue by Rozzemak** [hannesmann/vanillafixes#32]
This tool requires some VC redist, otherwise it does not inject into wow.exe and outputs some error regarding DllMain. I don't know exactly which version it needs but installing all of them from this site helped:
https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

Would be cool if correct dependency was listed in the installation process.

**Comment by hannesmann** [comment]
Both VanillaFixes.exe and VfPatcher.dll are statically linked to the Visual C++ runtime. They only depend on DLLs that are included with Windows. The dependency has to be coming from somewhere else (do you use [nampower](https://github.com/namreeb/nampower)?). 

![Screenshot 2023-10-01 131622](https://github.com/hannesmann/vanillafixes/assets/6569064/5b7902f5-71aa-4a2e-ad12-aec8a5c4e92b)
![Screenshot 2023-10-01 131654](https://github.com/hannesmann/vanillafixes/assets/6569064/74a1ccbe-cb6d-4ab6-abd6-e77400189573)

**Comment by Rozzemak** [comment]
Oh, the nampower dll was present in the directory. 
Thanks for the clarification about the dependencies.
