### ISSUE TITLE
low fps and 132 error in Stormwind City & Orgrimmar on Turtle-WoW 1.17 with VanillaFixes

### ISSUE THREAD

**Issue by Timolol2012** [hannesmann/vanillafixes#33]
After you arrive in Stormwind City & Orgrimmar, low fps, stay outside the auction house for a while, there is a high probability that a 132 error will appear.

This problem recurs on my 3 computers with different hardware.

If I start World of Warcraft without VanillaFixes.exe, 132 error will not appear.

**Comment by Timolol2012** [comment]
with VanillaFixes.exe 1.31, the chance of 132 error is greatly reduced,

But when i logout to charactor list and change another charactor login, 132 error will appear sometimes

**Comment by Timolol2012** [comment]
I never get the 132 error on everlook server with original 1.12.1 WoW.exe launched by VanillaFixes

**Comment by hannesmann** [comment]
Closing as this seems to be an issue with server modifications, not VanillaFixes.
