### ISSUE TITLE
FPS Drop since NVIDIA driver update to  546.01

### ISSUE THREAD

**Issue by Ge3e** [hannesmann/vanillafixes#36]
My whole screen goes black for 1-2 seconds when moving mouse out of window. It never did this before. I have only noticed it since NVIDIA updated their driver to 546.01 prior to this I had no issues. In addition to this I have had a massive FPS drop in general V Synced to 60FPS but only hovers around 40 FPS in world. I have a RTX 4070 so its not my card.

**Comment by hannesmann** [comment]
Closing since there haven't been any more reports of this in a while

**Comment by Nikki1993** [comment]
Had the same issue a month ago when I reinstall TWoW. Also just got a report from someone with AMD GPU having same issue. Removing `d3d9.dll` fixed the issue.
