### ISSUE TITLE
Scrollwheel up/down not working

### ISSUE THREAD

**Issue by thom4466** [hannesmann/vanillafixes#38]
I installed it on TurtleWoW and suddenly I couldnt use scrollwheel as in the game doesnt even register the action anymore, cant rebind it either.
Scrollwheel works fine if I just use the wow.exe instead so its only happening with vanillafixes.
Will gladly show on discord if it will help solve this problem.

**Comment by journeym** [comment]
using on turtle wow, scroll wheel is working

**Comment by hannesmann** [comment]
Closing since this doesn't seem to be caused by VanillaFixes and there haven't been any more reports of this problem
