### ISSUE TITLE
How to put add mouse camera jump fix Patch！

### ISSUE THREAD

**Issue by WuVenus** [hannesmann/vanillafixes#41]
How to put add mouse camera jump fix Patch！
![126278-caedc2cb052fb403c5629fa28442e70f](https://github.com/hannesmann/vanillafixes/assets/144596429/10596d03-a617-4cba-a84f-c604a7a7e846)
Add vanillafixes ？

**Comment by hannesmann** [comment]
Patch the EXE with [vanilla-tweaks](https://github.com/brndd/vanilla-tweaks) and follow the instructions [here](https://github.com/hannesmann/vanillafixes?tab=readme-ov-file#using-a-custom-executable). The easiest way to use the patched EXE is to drag WoW_tweaked.exe over VanillaFixes.exe.
