### ISSUE TITLE
Working with newer clients

### ISSUE THREAD

**Issue by pavyan** [hannesmann/vanillafixes#46]
I tried using VanillaFixes with MoP client from Stormforge Mistblade and it even seems to work (I will test some more to clarify tho)
But it doesnt run with their 64bit version of a client. Is there a way to fix that and make it work?

**Comment by Zebouski** [comment]
you misunderstand, theres no need for VF on anything but 2006 vanilla's old crappy client.

**Comment by hannesmann** [comment]
Closing since the question has been answered
