### ISSUE TITLE
Pattern for offsets 1.6.1-1.12.1

### ISSUE THREAD

**Issue by Daribon** [hannesmann/vanillafixes#49]
IDA patterns to find offsets between 1.6.1 and 1.12.1:
fnWowTimeKeeperThreadProc = 8B 0D ? ? ? ? E8 ? ? ? ? 56 8D 64 24
fnWowGetCPUFrequency = E8 ? ? ? ? 85 C0 74 ? A1 ? ? ? ? 8B 15 ? ? ? ? C3
fnWowReadTSC = 0F 31 C3 90 90 90 90 90 90 90 90 90 90 90 90 90 55 
g_pWowUseTSC XREF = A1 ? ? ? ? 85 C0 89 45 ? 75 
g_pWowTimerTicksPerSecond XREF = 8B 15 ? ? ? ? C7 45 ? ? ? ? ? 89 45 ? 89 75
g_pWowTimerToMilliseconds XREF = DC 0D ? ? ? ? DC 05 ? ? ? ? DD 45
g_pWowTimerOffset XREF = DC 05 ? ? ? ? E8 ? ? ? ? 8B E5

Offsets for 1.6.1:
fnWowTimeKeeperThreadProc 0x00421460
fnWowHwGetCpuFrequency 0x421B50
fnWowReadTsc 0x0041FA80
g_pWowUseTsc 0x00807448
g_pWowTimerTicksPerSecond 0x007BD470
g_pWowTimerToMilliseconds 0x007BD478
g_pWowTimerOffset 0x00807450

Offsets for 1.7.1:
fnWowTimeKeeperThreadProc 0x00421F80 
fnWowHwGetCpuFrequency 0x00422620
fnWowReadTsc 0x0041FA90
g_pWowUseTsc 0x00811A30
g_pWowTimerTicksPerSecond 0x007C67B0
g_pWowTimerToMilliseconds 0x007C67B8
g_pWowTimerOffset 0x00811A38

If you want I can post the offsets for the other patches too, since it only takes a couple of minutes to find.

**Comment by hannesmann** [comment]
Added in 266b2dd617f3bf9fe0fe7372ec728462b26ed139
