### ISSUE TITLE
Second Windows screen flickers/black screen 

### ISSUE THREAD

**Issue by Morons** [hannesmann/vanillafixes#50]
I have a duel screen set-up

I find using Vinilla (Either versions) cause the window second screen to go black and then re-initialise after a while each time I switch my focus (click) on the second screen and again switching back to the Maxed-Windowed client.

I use the second screen for QOL such as wiki etc.

**Comment by hannesmann** [comment]
This sounds like a duplicate of #36. Try removing DXVK (d3d9.dll) and see if that changes anything.

**Comment by Morons** [comment]
> This sounds like a duplicate of #36. Try removing DXVK (d3d9.dll) and see if that changes anything.

Fixed Thanx for the tip
