### ISSUE TITLE
Ability Rewrite definition of dxvk and dsoal to dll.txt

### ISSUE THREAD

**Issue by shikulja** [hannesmann/vanillafixes#59]
It is necessary to download from under a subdirectory so that the root directory is cleaner (including log cache)

will also allow you to manage the disabling of libraries, without renaming or deleting

```
# If you use dxvk (https://github.com/doitsujin/dxvk), it will be loaded by this lines
#mods\dxvk\dxgi.dll
#mods\dxvk\d3d9.dll

# If you use dsoal (https://github.com/ThreeDeeJay/dsoal/releases/tag/latest-c%2B%2B-rewrite), it will be loaded by this lines
#mods\dsoal\dsound.dll
#mods\dsoal\dsoal-aldrv.dll
```

not sure about dxgi.dll and dsoal-aldrv.dll (and their priority)

**Comment by hannesmann** [comment]
DXVK and DSOAL are loaded by the game from d3d9.dll and dsound.dll. I don't think VanillaFixes can change this without patching the executable.
