### ISSUE TITLE
[sugession] New build with DSOAL support

### ISSUE THREAD

**Issue by shikulja** [hannesmann/vanillafixes#6]
dxvk+DSOAL+OpenAL

repo:
https://github.com/kcat/dsoal

builds:
https://ci.appveyor.com/project/ChrisRobinson/dsoal
https://github.com/kcat/dsoal

**Comment by hannesmann** [comment]
Does this do anything other than enable 3D sound? It seems pretty easy to set up, I don't think it needs to be included with VanillaFixes (I only included DXVK because it improves performance).

**Comment by hannesmann** [comment]
Added in v1.3.
