### ISSUE TITLE
How about use DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE instead of V2

### ISSUE THREAD

**Issue by allfoxwy** [hannesmann/vanillafixes#61]
By https://learn.microsoft.com/en-us/windows/win32/hidpi/dpi-awareness-context

DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 requires Windows 10 1703. And in fact we didn't implement anything it provides.

DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE is already enough to disable automatic scaling. It requires Windows 10 1607.

I think lower the requirement is better.

**Comment by hannesmann** [comment]
`SetProcessDPIAware` takes care of scaling the game window (this is the method DXVK uses). The only advantage of `DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2` is that it makes the message boxes in the launcher DPI-aware.
