### ISSUE TITLE
DXKV 2.5 Release - Will this be updated?

### ISSUE THREAD

**Issue by 8EightySixed6** [hannesmann/vanillafixes#65]
DXKV 2.5 Release - Will this be updated?

**Comment by Chromos-Def** [comment]
You should be able to update it yourself by going to the DXVK repo and using the d3d9.dll inside of the x32 folder.
https://github.com/doitsujin/dxvk/releases

**Comment by hannesmann** [comment]
Updated to 2.5.1.
