### ISSUE TITLE
vanillafixes-1.2-dxvk.zip

### ISSUE THREAD

**Issue by zoppablue** [hannesmann/vanillafixes#7]
I keep getting black flashes on my screen when I alt tab from the game.

But on the other version 'vanillafixes-1.2.zip' it works fine.

**Comment by shikulja** [comment]
You need to tell us what operating system you are using dxvk on.
Also dxvk uses full screen exclusive mode. Switching video mode may result in a black screen at the time of switching. This shouldn't be a problem.
Regarding dxvk, I recommend writing a problem report in the dxvk thread, attaching a log and a full description of the problem.

**Comment by hannesmann** [comment]
Sounds like a DXVK/driver problem. I updated the zip file to DXVK 2.1 so you can try redownloading and see if that helps. Also, like shikulja said, DXVK uses exclusive fullscreen so a quick black flash when alt-tabbing is expected.

**Comment by zoppablue** [comment]
Windows 10, x64.

I downloaded the non DXVK version of the vanillafixes file, and downloaded the DXVK 2.1 version from https://github.com/doitsujin/dxvk/releases

The black flash has now gone.
